// English dictionary. Korean is the source language in the engine and content files; this file maps it to English.

export const UNIT_EN: Record<string, string> = {
  "조원": "KRW tn", "조원/년": "KRW tn/yr", "조원(2025가격)": "KRW tn (2025 prices)", "조원/TWh": "KRW tn/TWh", "비율": "ratio", "/년": "/yr",
  "계수": "coef.", "스위치": "switch", "선택": "choice", "년": "years", "원/kWh": "KRW/kWh", "천원/kW": "KRW '000/kW", "배": "×", "원/t": "KRW/t",
  "원/GJ": "KRW/GJ", "원/USD": "KRW/USD", "Mt/천원": "Mt per KRW 1,000", "Mt/년": "Mt/yr", "pp/년": "pp/yr", "탄력성": "elasticity",
  "비중/금리(분수)": "share per rate gap", "%/%": "%/%", "pp/pp": "pp/pp",
};

export const GROUP_EN: Record<string, string> = {
  init: "Initial values · national accounts (2025)", hh: "Households (consumption · portfolio)", nfc: "Non-financial firms (investment · green share · credit)",
  bank: "Banks · interest spreads", mon: "Monetary policy rule", price: "Prices · exchange rate", gov: "Government · fiscal rule",
  power: "Power sector (megaprojects · supply · tariffs)", tech: "Generation technology costs", ets: "K-ETS · abatement route", kgx: "K-GX budget · policy finance", eco: "Ecology · physical damage",
};

export const SECTOR_EN: Record<string, string> = { HH: "Households", NFC: "Non-fin. firms", PS: "Power sector", BK: "Banks", PB: "K-GX policy finance", GOV: "Government", CB: "Bank of Korea", ROW: "Rest of world" };
export const INSTR_EN: Record<string, string> = {
  Cash: "Cash", Res: "Reserves", Dep: "Deposits", Ln_nfc: "Firm bank loans", Ln_ps: "Power-sector borrowing", Ln_hh: "Household loans", PBL: "Policy loans",
  PBE: "Policy equity", PBB: "Policy-bank bonds", Bond: "Government bonds", Adv: "BOK advances (− MSBs)", FXR: "FX reserves",
};
export const RULE_EN: Record<string, string> = {
  define: "DEFINE-UK rule (eq. 427, lagged inflation)", taylorH: "Taylor: headline CPI", taylorC: "Taylor: core (look-through)",
  ait: "Adaptive inflation targeting (band · averaging)", fixed: "Fixed rate path",
};
export const DESIGN_EN: Record<string, string> = {
  admin: "Administered tariff · single buyer (current)", cfd: "CfD · long-term contracts (pass-through)", pool: "Marginal-price pool (DEFINE-UK market price)",
};
export const SUPPLY_EN: Record<string, string> = {
  G: "G: gas-led", R: "R: renewables-led (gas firming)", M: "M: mixed", N: "N: nuclear · SMR (2033+, gas bridge)",
};
export const REF_EN: Record<string, string> = {
  noMP: "No megaprojects (same settings)", noKGX: "No K-GX (same settings)", pinned: "Pinned case A", baseRule: "Default (Taylor · administered · G)",
};

export const TX_EN: Record<string, string> = {
  "소비: 비전력 재화": "Consumption: non-electricity goods", "소비: 가계 전기요금": "Consumption: household electricity bills",
  "기업 전기요금(DC 포함, 지역요금 경감 후)": "Firm electricity bills (incl. DCs, after regional relief)", "지역요금제 재정보전": "Budget compensation for regional tariffs",
  "정부소비(R&D 포함)": "Government consumption (incl. R&D)", "투자재: 전력부문(국내분)": "Investment goods: power sector (domestic)", "투자재: 정부": "Investment goods: government",
  "수출": "Exports", "수입: 비에너지": "Imports: non-energy", "수입: 비전력 에너지": "Imports: non-power energy", "수입: 발전연료(LNG·석탄)": "Imports: power fuel (LNG · coal)",
  "수입: 전력 설비 수입분": "Imports: power equipment", "전력부문 중간투입(국내)": "Power-sector intermediate inputs (domestic)",
  "임금: 기업": "Wages: firms", "임금: 전력부문": "Wages: power sector", "생산·수입세": "Taxes on production and imports", "법인세(세액공제 차감 후)": "Corporate tax (net of tax credit)",
  "법인세: 전력부문": "Corporate tax: power sector", "소득세": "Income tax", "사회보험료": "Social contributions", "사회수혜금": "Social benefits",
  "배출권 유상할당: 전력": "Allowance auctions: power", "배출권 유상할당: 산업": "Allowance auctions: industry", "배출권 매입(워터베드)": "Allowance purchases (waterbed)", "ITMO 구매": "ITMO purchases",
  "이자: 기업 은행대출": "Interest: firm bank loans", "이자: 기업 정책대출(순)": "Interest: firm policy loans (net)", "이자: 전력부문 차입": "Interest: power-sector borrowing",
  "이자: 전력부문 정책대출(순)": "Interest: power-sector policy loans (net)", "이자: 가계대출": "Interest: household loans", "이자: 예금(가계)": "Interest: deposits (households)",
  "이자: 예금(기업)": "Interest: deposits (firms)", "이자: 예금(전력)": "Interest: deposits (power)", "이자: 예금(해외)": "Interest: deposits (non-residents)",
  "이자: 국채(가계)": "Interest: bonds (households)", "이자: 국채(은행)": "Interest: bonds (banks)", "이자: 국채(한은)": "Interest: bonds (BOK)", "이자: 국채(해외)": "Interest: bonds (non-residents)",
  "이자: 정책금융채": "Interest: policy-bank bonds", "이자: 한은 대출": "Interest: BOK advances", "이자: 외환보유액": "Interest: FX reserves", "이차보전(K-GX)": "Interest subsidy (K-GX)",
  "보증료": "Guarantee fees", "배당: 기업": "Dividends: firms", "배당: 은행": "Dividends: banks", "배당: 전력부문(정부)": "Dividends: power sector (government)",
  "배당: 전력부문(민간)": "Dividends: power sector (private)", "한은 잉여금 납부": "BOK profit transfer",
  "자본이전: 녹색투자 보조금(K-GX)": "Capital transfer: green investment grants (K-GX)", "자본이전: 전력 청정투자 보조(K-GX)": "Capital transfer: power clean-investment grants (K-GX)",
  "자본이전: 국내감축 보조": "Capital transfer: domestic abatement subsidy", "자본이전: 정책금융기관 출자": "Capital transfer: equity injection into policy banks",
  "자본이전: 은행 부실채권 상각": "Capital transfer: bank loan write-offs", "자본이전: 보증 대위변제": "Capital transfer: guarantee calls",
  "자본이전: 보증부 대출 상각": "Capital transfer: guaranteed-loan write-offs", "자본이전: 정책대출·지분 손실(기업)": "Capital transfer: policy loan/equity losses (firms)",
  "자본이전: 정책대출·지분 손실(전력)": "Capital transfer: policy loan/equity losses (power)",
};

// parameter labels / sources / notes: [label, source?, note?]
export const PARAM_EN: Record<string, [string, string?, string?]> = {
  Y0: ["Nominal GDP 2025", "S23 BOK national accounts 2025 (prelim.)"],
  sh_C: ["Household consumption / GDP", "BOK national accounts (approx.)"], sh_G: ["Government consumption / GDP", "BOK national accounts (approx.)"],
  sh_Igov: ["Government investment / GDP", "Approximation"], sh_X: ["Exports / GDP", "Approximation"],
  sh_Men: ["Non-power energy imports / GDP", "Energy imports ~KRW 250 tn − power fuel"], Ips0: ["Other power-sector investment (grid · existing plant) 2025", "KEPCO group capex (approx.)"],
  K_nfc0: ["Firm capital stock, end-2024", "L2 S0_Kc+S0_Kg"], K_ps0: ["Power-sector capital stock, end-2024", "Approximation"], K_gov0: ["Government capital stock, end-2024", "Approximation"],
  gK_share0: ["Green share of firm capital, end-2024", "L2 700/8500"], u0: ["Capacity utilisation 2025", "DEFINE u_T convention"],
  Lh0: ["Household loans, end-2024", "L2 S0_Lh"], Lnfc0: ["Firm bank loans, end-2024", "L2 S0_Lg+S0_Lc"], Lps0: ["Power-sector borrowing (KEPCO bonds etc.), end-2024", "KEPCO consolidated debt (approx.)"],
  Dnfc0: ["Firm deposits, end-2024", "Approximation"], Hh0: ["Household cash, end-2024", "L2 S0_Hh"], B0: ["Government debt, end-2024", "S24 2026 budget · national debt"],
  sh_I: ["Total investment / GDP 2025", "BOK national accounts (approx.)"], Bcb0: ["BOK holdings of government bonds", "L2 S0_Bcb"], b_row: ["Non-resident share of government bonds", "Approximation"],
  Ebk0: ["Bank equity, end-2024", "Set to CAR ≈ 14.5%"], Adv0: ["BOK advances (−: MSBs), end-2024", "L2 S0_A"], Drow0: ["Non-resident deposits, end-2024", "Approximation"],
  alpha2: ["Propensity to consume out of net financial wealth α2", "Near L2 alpha2 (0.03); α1 calibrated to 2025", "DEFINE eq. 346 is an ECM; here a Godley-Lavoie level equation + 2025 calibration"],
  tau_h: ["Effective tax rate on household income", "Near L2 tau_h"], tau_ss: ["Social contribution rate (wages)", "Approximation"], cash_c: ["Cash / consumption", "L2 cash"],
  lambda1: ["Bond portfolio response to rate gap", "Tobin portfolio"], tr_share: ["Social benefits / lagged GDP", "Approximation"],
  delta_k: ["Depreciation of firm capital", "Near DEFINE δ = 0.024/quarter"], a_u: ["Investment response to utilisation α1", "DEFINE eq. 183 form"],
  a_p: ["Investment response to profit rate", "DEFINE · Dafermos 2017 investment function form"], a_r: ["Investment response to real lending rate", "Dafermos 2017 investment function form"],
  s_f: ["Firm retention ratio", "L2 sf"], tau_f: ["Effective corporate tax rate", "L2 tau_f"], tau_ind: ["Taxes on production / firm value added", "Approximation"],
  omega: ["Wage share in firm value added", "Near L2 omega 0.47 (GDP basis)"], theta0: ["Green share of investment 2025", "L2 theta0"],
  b_tau: ["Green-share response to carbon price (logit, per KRW 10k/t)", "L2 eta_tau"], b_r: ["Green-share response to green–conventional rate gap (logit, per pp)", "L2 eta_r; GDCR channel"],
  b_trend: ["Autonomous green-share trend (logit/yr)", "DEFINE TREND term"], cr_on: ["Credit rationing on (1/0)", "DEFINE eqs. 224–225"], cr_max: ["Maximum credit rationing CRmax", "DEFINE CRmax form"],
  cr_dsr: ["Credit rationing sensitivity to debt-service ratio r2", "DEFINE r2"], cr_car: ["Credit rationing sensitivity to capital ratio r3", "DEFINE r3"],
  def0: ["Baseline default rate on firm loans", "DEFINE eq. 203 form (linearised)"], def_dsr: ["Default-rate sensitivity to DSR", "DEFINE eq. 203"],
  sL: ["Spread on firm loans", "L2 spread_L 1.5%+"], sLh: ["Spread on household loans", "Approximation"], sD: ["Deposit rate = policy rate − sD", "L2 spread_D"],
  s_ps: ["Power-sector borrowing spread over government bonds", "KEPCO–KTB spread (approx.)"], term: ["Term premium on government bonds", "Approximation"],
  kappa_B: ["Adjustment speed of average bond yield κB", "L2 kappa_B"], rr: ["Reserve requirement ratio", "L2 rr"], bb: ["Bank government bonds / deposits", "Approximation"],
  s_b: ["Bank retention ratio", "Approximation"], rw_c: ["Risk weight: conventional firm loans", "Basel standard"], rw_g: ["Risk weight: green firm loans", "Basel standard"],
  rw_h: ["Risk weight: households", "Basel mortgages"], rw_ps: ["Risk weight: power sector", "Quasi-sovereign treatment"],
  gdcr: ["Green-differentiated capital requirement (GDCR) risk-weight gap", "Dafermos & Nikolaidi 2021 (LA-A5)", "Green rw −gdcr, conventional rw +gdcr; converted to spreads via cost of capital χ"],
  chi: ["Spread per unit of risk weight (cost of equity × required capital ratio)", "Approximation"],
  i0: ["Policy rate 2025", "BOK base rate 2025"], pi_star: ["Inflation target", "BOK 2% target"], rstar: ["Neutral real rate", "Approximation"],
  phi_pi: ["Inflation-gap response φπ", "S17 · S16 (Korea 0.30–2.06)"], phi_y: ["Utilisation-gap response φy", "S16 Lee & Joo 2022"], rho_i: ["Interest-rate smoothing ρ", "L1 MO_smooth"],
  eps_r: ["DEFINE rate adjustment speed ε_rboe", "DEFINE eq. 427 form"], alpha_r: ["DEFINE rate–inflation elasticity α_rboe", "Steady state r = INF^α: 2% → 2.5%"],
  ait_band: ["AIT tolerance band half-width", "E01 Barmes et al. 2024 p31 (≤2pp)"], ait_h: ["AIT averaging horizon", "E01 Table 5.1 (2 → 3+ years)"],
  di_exo: ["Exogenous shift of rate path (global tightening)", "E02 Schmidt 2019 experiment"],
  lam_e: ["Anchoring of inflation expectations to target λ", "Simplified expectations term of MFMod price ECM"], kappa_u: ["Phillips: utilisation gap → core inflation", "DEFINE eqs. 56–58 markup–utilisation"],
  w_el: ["CPI weight of electricity", "S13 Statistics Korea 2022 base"], io_el: ["1% electricity price → core (indirect, %)", "S14×0.75×0.7 (L1 PR_io_ind·share·margin); Choi 2013 ~4× higher"],
  w_fu: ["CPI weight of fuels (oil products · city gas)", "Statistics Korea weights (approx.)"], th_fu: ["Imported fuel price → consumer fuel pass-through", "Dilution by taxes and margins"],
  io_fu: ["1% fuel price → core (indirect, %)", "López et al. 2024 (ECB) indirect share"], th_fx: ["1% FX depreciation → core inflation (%)", "Range of BOK FX pass-through estimates"],
  eps_x: ["1% FX depreciation → exports (%)", "Approximation"], g_world: ["Nominal growth of world demand", "Approximation"],
  g_prod: ["Trend growth of capital productivity (potential/capital)", "Reduced form of DEFINE labour-productivity trend"], g_pot: ["Potential real growth (expected)", "Approximation"],
  fx_shock: ["FX shock (KRW depreciation, shock years)", "Q4 LNG · FX channel"], gas_shock: ["LNG price shock multiplier (shock years)", "S12; 2022-type = 2"],
  shock_y0: ["Shock start year", "L1 PR_shock_y0"], shock_y1: ["Shock end year", "L1 PR_shock_y1"], i_world: ["Return on FX reserves", "Approximation"],
  g_drift: ["Drift of non-green government consumption share", "L2 g_drift (ageing)"], d_star: ["Fiscal-rule debt threshold", "Proposed fiscal rule 60%"], kappa_f: ["Fiscal-rule adjustment strength", "Approximation"],
  prem_on: ["Sovereign risk premium on (1/0)", "Inactive in MFMod base closure"], mu1: ["Sovereign premium per pp of debt ratio", "E03 Canelli 2024 (Italy estimate)"],
  alpha_off: ["Weight of off-balance-sheet exposure in premium", "E04 IMF SRDSF perimeter concept"], ps_gov_div: ["Government share of power-sector dividends", "Government stake in KEPCO (approx.)"],
  mp_on: ["Include megaproject increment (1/0)", "Research design"], LD_2029: ["AI data-centre capacity 2029", "S06 MSIT 2026-06-29"], LD_2035: ["AI data-centre capacity 2035", "S06"],
  LD_semi: ["Additional semiconductor-cluster load 2035 (optional)", "Semiconductor cluster 6.3 GW (announced); 27.7 GW total unconfirmed"],
  dc_rev: ["Share of DC electricity bills funded by DC service revenue (exports)", "Megaproject business case out of scope", "1 = DC bills do not crowd out other firms' demand; 0 = net cost"],
  LD_real: ["Realisation of announced capacity", "L1 LD_08"], LD_lf: ["Load factor", "S07 back-calculated from 12th plan outlook"],
  LD_emb2030: ["DC demand embedded in 11th Basic Plan, 2030", "S01"], LD_emb2038: ["DC demand embedded in 11th Basic Plan, 2038", "S01"],
  sales0: ["Electricity sales 2024", "S45"], g_sales: ["Baseline sales growth", "S34"], hh_el_share: ["Household share of electricity use", "KEPCO statistics (approx.)"],
  tariff0: ["Average retail tariff 2024", "S19"], nuc0: ["Nuclear generation 2025", "Approximation"], nuc2038: ["Nuclear generation 2038 (11th plan)", "11th Basic Plan (approx.)"],
  coal0: ["Coal generation 2025", "Approximation"], coal_cut: ["Coal generation cut by 2040", "11th plan · coal phase-down (approx.)"], coal_cost: ["Coal fuel cost", "~USD 120/t"],
  coal_ef: ["Coal emission factor", "S44"], re2025: ["Renewable capacity 2025", "S01"], re2030: ["Renewable capacity 2030 (11th plan)", "S01"], re2038: ["Renewable capacity 2038 (11th plan)", "S01"],
  kgx_re100: ["Apply K-GX 100 GW renewables target for 2030 (1/0)", "K-GX press release 2026-10-07"], re_cf: ["Weighted capacity factor of renewable pipeline", "L1 MO_re_cf"],
  re_eps: ["Elasticity of renewable build-out to LCOE ε", "L1 MO_eta"], re_cap_x: ["Cap on renewable build-out (× plan)", "Siting · grid constraints"],
  mo_beta: ["Pass-through of policy rate to project WACC β", "S15 BOK blog"],
  rp_cfd: ["Risk premium under CfD / long-term contracts (vs administered tariff)", "Egli 2018 · Polzin 2021 (direction)", "Q3 hypothesis: single buyer and administered prices constrain IPP bankability (untested)"],
  rp_pool: ["Risk premium under marginal-price pool (no contracts)", "Merchant risk"], sigma: ["Share of incremental system cost socialised σ", "S36; L1 PR_sigma"],
  rho_t: ["Regulated tariff pass-through ρ", "L1 PR_rho"], lag_t: ["Tariff adjustment lag", "S30"], step_t: ["Tariff adjustment interval (bunched steps)", "S31"], ratchet: ["Tariff ratchet (no cuts)", "S31"],
  mu_mprice: ["DEFINE marginal-price curvature μ", "DEFINE eq. 91"], net_charge: ["Network · retail charge (pool design)", "Approximation"], ps_wage: ["Power-sector wage share (value added)", "Approximation"],
  delta_ps: ["Depreciation of power capital", "Approximation"], endo_mix: ["Endogenous incremental supply mix (1/0)", "DEFINE eq. 109 propNFF logit", "Q3: private investment response to prices and market rules"],
  b0_mix: ["Clean-share logit intercept", "Approximation"], b1_mix: ["Clean-share response to relative return (LCOE gap %)", "DEFINE α1bNFF form"],
  int_on: ["Endogenous intermittency firming (GMMET-type) (1/0)", "GMMET intermittency · storage need"], fi_base: ["Baseline gas firming share φ", "S27 24/7 CFE studies"],
  fi_slope: ["Increase in firming share per unit of system VRE share", "GMMET intermittency treatment (form)"], sto_ratio: ["Storage GW per GW of VRE", "S01"],
  sto_slope: ["Increase in storage ratio per unit of system VRE share", "GMMET (form)"], reg_tariff_on: ["Regional industrial tariffs (south −10%) (1/0)", "MCEE · KEPCO design 2026-08-26"],
  reg_relief: ["Industrial bill relief from regional tariffs", "MCEE estimate KRW 2.8 tn (2026-08-26)"], reg_fund: ["Funding of relief: 0 = power sector absorbs, 1 = budget, 2 = cross-subsidy", "Design choice"],
  cx_solar: ["Solar PV capex", "S10 KEEI 2024"], cx_on: ["Onshore wind capex", "S10"], cx_off: ["Offshore wind capex", "S10"], cx_gas: ["LNG CCGT capex", "S11"],
  cx_nuc: ["Nuclear · SMR capex", "Approximation (SMR uncertain)"], cx_sto: ["Battery storage capex", "S35"], cx_grid: ["Grid cost per kW of incremental load", "L1 TC_grid_cost"],
  cf_solar: ["Solar PV capacity factor", "S10"], cf_on: ["Onshore wind capacity factor", "S10"], cf_off: ["Offshore wind capacity factor", "S10"], cf_gas: ["Gas capacity factor (DC baseload)", "S11"],
  cf_nuc: ["Nuclear capacity factor", "Approximation"], gas_eff: ["CCGT thermal efficiency", "S11"], gas_price: ["Gas price for power", "S12 KOGAS 2026-09"], gas_ef: ["LNG emission factor", "S44"],
  w0: ["Baseline WACC", "S10"], sK_re: ["Capital share of renewable LCOE", "PR-13 structure"], mimp_solar: ["Import share of solar capex", "MFMod electricity capex import content (form)"],
  mimp_wind: ["Import share of wind capex", "MFE (form)"], mimp_gas: ["Import share of gas capex", "MFE (form)"], mimp_nuc: ["Import share of nuclear capex", "MFE (form)"], mimp_sto: ["Import share of storage capex", "MFE (form)"],
  ets_mode: ["K-ETS cap response: 0 = accommodating (state closes gap), 1 = rigid (waterbed)", "S32 · S47; L1 EM_cap_mode"], gap_route: ["Gap-closing route: 0 = ITMO purchases, 1 = domestic abatement (K-GX subsidy)", "L1 EM_gap_route"],
  kau2026: ["KAU price 2026", "S20"], kau_g: ["Real KAU price growth", "L1"], kau_ceiling: ["K-MSR soft price ceiling", "S46"], kau_slope: ["Extra abatement per KRW 1,000 KAU rise (MAC slope)", "Own assumption"],
  auction0: ["Power-sector auction share 2026", "S32"], auction2030: ["Power-sector auction share 2030", "S32 15% → 50%"], itmo_usd: ["ITMO unit price", "S21; README §6: review 30"],
  itmo_cap: ["State ITMO procurement cap (megaproject share)", "L1 ITMO_cap"], mac_dom_usd: ["Domestic shadow marginal abatement cost", "S22 Kim et al. 2023"], fx0: ["Exchange rate", "L1"],
  em2024: ["National net emissions 2024", "S03"], em_power2024: ["Power-sector emissions 2024", "S05"], em_decay: ["Autonomous decline of non-power emission intensity", "Approximation"],
  auction_ind: ["Industry auction share", "Near 10% in phase 3"], em_green: ["Non-power intensity reduction per unit of green capital share", "Linearised DEFINE eq. 26 logistic"],
  kgx_on: ["Include K-GX package (1/0)", "K-GX 2026-10-07"], kgx_budget: ["K-GX budget (2026–2035 total)", "K-GX press release: budget KRW 200 tn"],
  kgx_pf: ["K-GX climate finance (five policy finance institutions, total)", "K-GX: KRW 790 tn+ (KDB · IBK · KEXIM · KODIT · KIBO)"], kgx_pf2026: ["Policy finance supply target 2026", "S04 FSC"],
  kgx_priv: ["Private signature investment (total)", "K-GX: 10 signature projects, KRW 220 tn"], al_grant: ["Budget: green investment grants to firms", "Allocation unpublished — assumption"],
  al_psgrant: ["Budget: power clean-investment grants", "Assumption"], al_rnd: ["Budget: R&D · industrial support (government consumption)", "Assumption"],
  al_ptc: ["Budget: domestic production tax credit", "From 2027; tapers to 75% (2034), 50% (2035), 25% (2036)"], al_isub: ["Budget: interest subsidies", "MCEE 2027 support plan"],
  al_inj: ["Budget: equity injections into policy banks", "Assumption"], al_pubinv: ["Budget: public green investment", "Assumption"],
  pf_loan: ["Loan share of policy finance", "Instrument split unpublished — near FISCAL FK_share"], pf_guar: ["Guarantee share of policy finance", "KODIT · KIBO share (approx.)"],
  pf_ps: ["Power-sector share of policy finance", "Assumption"], pf_tenor: ["Average tenor of policy loans", "L1 FI_tenor"], pf_spread: ["Policy loan rate = government bond + spread", "Approximation"],
  pbb_spread: ["Policy-bank bond rate = government bond + spread", "KDB bond spread (approx.)"], pf_el: ["Expected loss rate on policy loans", "FISCAL FG_EL_loan"],
  guar_el: ["Expected loss rate on guarantees (pd × lgd × cover)", "FISCAL"], guar_fee: ["Guarantee fee rate", "KODIT average fee (approx.)"], guar_tenor: ["Average guarantee tenor", "Approximation"],
  add_grant: ["Additionality of grants (extra green investment per grant)", "To be estimated in Track A2"], add_ptc: ["Additionality of tax credits", "To be estimated in Track A2"],
  add_pf: ["Additionality of policy finance (loans · equity)", "Track A2: supply ≠ mobilisation ≠ additionality"], add_guar: ["Additionality of guarantees (per outstanding)", "Track A2"],
  add_priv: ["Additionality of private signature projects", "Announced ≠ executed"], hybrid: ["Upfront subsidy deducted from later tax credit (hybrid) (1/0)", "Presidential proposal 2026-10-07, not adopted"],
  green_bond: ["Green government bonds (from 2028) (1/0)", "K-GX: first issue 2028"], fiscal_rule: ["Fiscal rule: 0 = none, 1 = debt rule (cuts green too), 2 = adaptive (protects green)", "Pereira da Silva 2025 (LA-B14)"],
  dmg_on: ["Physical climate damages on (1/0)", "Dafermos et al. 2017 damage function"], T2025: ["Global warming 2025", "WMO (approx.)"], T2050: ["Global warming 2050 (exogenous)", "NGFS current policies (approx.)"],
  eta2: ["Damage function η2", "Dafermos et al. 2017 (Weitzman 2012)"], eta3: ["Damage function η3 (exponent 6.754)", "Dafermos et al. 2017"],
  p_prod: ["Share of damage hitting productivity p", "Dafermos et al. 2017 eq. 56 (p = 0.1)"], adK: ["Adaptation of capital damage", "Dafermos et al. 2017 App. B"], adP: ["Adaptation of productivity damage", "Dafermos et al. 2017 App. B"],
};
